### ISSUE TITLE
Spring Cloud Alibaba 2.2.0 web URLs cannot be extracted when using with Shiro

### ISSUE THREAD

**Issue by 89333367** [alibaba/Sentinel#1279]
后面不用看了，我降级到2.1.1.RELEASE版本就可以了，看来2.2.0版本有bug

dashboard项目已经部署，能启动，看到页面；
另一个项目，添加了
```
<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
            <version>2.2.0.RELEASE</version>
        </dependency>
spring.cloud.sentinel.transport.dashboard=localhost:20000
```
只能监控到
```
/
/login
/logout
```
这三个url，其他的url点了好多次了，监控页面上也没有
 只有登陆页面的url和登出页面的url可以监控到，其他url都监控不到；

当我把 @SentinelResource 注解写道每一个方法上，就可以监控到了。
但是我的项目确实是springboot项目，为啥不能自动呢？

项目中用了shiro，跟这个有关系么？

**Comment by xue8** [comment]
Could you provide a demo to reproduce this problem?

**Comment by 89333367** [comment]
> Could you provide a demo to reproduce this problem?

不知道您想看哪部分代码，我直接把项目所有源码发出来吧。

> https://github.com/89333367/demo/tree/master/integration-bigdata-admin

**Comment by xue8** [comment]
The cause of this problem is `spring-cloud-starter-alibaba-sentinel` used `SentinelWebInterceptor` to replace `CommonFilter` in the version `2.2.0`. 

alibaba/spring-cloud-alibaba#1171

Because `Shiro` is used filters for authentication, and `CommonFilter` also uses filters, so `CommonFilter` can filter before `Shiro`, which is why your project can see other URLs in the version `2.1.1`. 
Since version `2.2.0` using `SentinelWebInterceptor` instead of `CommonFilter`, the interceptor is executed after the filter, so other URLs are redirected to `/login` by Shiro.

The filter and interceptor execution sequence is shown in the figure.
![](https://user-gold-cdn.xitu.io/2020/2/12/17038503892d3330?w=1150&h=876&f=png&s=212268)

**Comment by 89333367** [comment]
哦，看来是跟  shiro   有关了，那有简单的解决办法么？我需要怎样改动代码才能使用最新的2.2.2版本？

**Comment by pigxcloud** [comment]
试试配置一下 url-patterns 改成 `/**` 默认的是 `/*`  所有其他的都不拦截 

```
spring:
  cloud:
    sentinel:
      filter:
        url-patterns: /**
```

**Comment by 89333367** [comment]
> 试试配置一下 url-patterns 改成 `/**` 默认的是 `/*` 所有其他的都不拦截
> 
> ```
> spring:
>   cloud:
>     sentinel:
>       filter:
>         url-patterns: /**
> ```

多谢，我测试了一下，确实可以了，在shiro中，需要配置 /**
