### ISSUE TITLE
关于控制台的高可用，以及规则广播推送。

### ISSUE THREAD

**Issue by yangfanchuhai** [alibaba/Sentinel#142]
目前控制台的规则以及机器信息都是存储在内存，而且关于规则推送只能根据主机IP和端口推送。如果要实现控制台的高可用和规则的持久化，还需要进行定制化开发。
还有就是有关于规则推送，是否可以支持控制台关于规则分发源(如ZK等)的可扩展性和客户端拉取的DataSource对应起来。不然，如果业务方自己去实现DataSource还要去第三方配置中心如ZK上配置规则，易用性和体验不佳。或者自己开发一个控制台去对接配置中心。
将来有这方面支持的计划吗？

**Comment by yangfanchuhai** [comment]
目前来看，如果要在生产环境把布署起来，还是需要一些定制化的开发工作。

**Comment by sczyh30** [comment]
Sentinel Dashboard 是用于展示 Sentinel 基本功能的控制台，若希望在生产环境中使用则需自行进行改造：

- 推送维度按照应用维度推送
- 自行实现监控数据持久化（0.2.0 版本提供了 `MetricsRepository` 接口）
- 由于不同的场景下，使用的配置中心也不同，因此规则推送适配配置中心的逻辑需要自行进行改造
- 权限控制方面，需要自行实现

---

Hi, Sentinel Dashboard is a sample dashboard showing the basic functionality of Sentinel, not a solution for out-of-box production use. You have to modify the dashboard to use it in production.

For metrics persistence, we've provided a `MetricsRepository` interface in 0.2.0 and you can implement your own metrics persistence.

For pushing rules, due to the fact that config source is different in different circumstances (e.g. ZooKeeper, Nacos), we don't provide integration with config center in Sentinel Dashboard now.

**Comment by sczyh30** [comment]
More information can be found in the blog post: [在生产环境中使用 Sentinel 控制台](https://github.com/alibaba/Sentinel/wiki/%E5%9C%A8%E7%94%9F%E4%BA%A7%E7%8E%AF%E5%A2%83%E4%B8%AD%E4%BD%BF%E7%94%A8-Sentinel-%E6%8E%A7%E5%88%B6%E5%8F%B0)
