### ISSUE TITLE
持久化动态流控下发疑问

### ISSUE THREAD

**Issue by Childe-Chen** [alibaba/Sentinel#149]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
我对多个资源进行流控，在控制台上只对其中一个资源修改了流控规则，应用重启后，从持久化（zk）获取的流控规则把本地初始化流控规则全部覆盖。

### Describe what you expected to happen
应该是只会覆盖相同流控资源的规则，而不是全部以配置的为准。

### How to reproduce it (as minimally and precisely as possible)

1. 应用内初始化资源的流控规则
2. 在控制台新增初始化资源中某个资源的流控规则
3. 应用内初始化的规则被控制台创建的规则覆盖

### Anything else we need to know?
我看了下FlowRuleManager中configUpdate(List<FlowRule> value)的方法实现，发现只要loadFlowConf(List<FlowRule> list)返回不为null就会更新本地配置，但是loadFlowConf(List<FlowRule> list)中一定会返回一个不为null的Map。这就导致了flowRules被完全覆盖，导致本地配置丢失。

**Comment by sczyh30** [comment]
RuleManager 更新内存态的规则时会进行 **全量更新** 而不是 合并更新，因此要保证动态规则源中存储的规则为全量规则。控制台结合配置中心（如 ZooKeeper）推送需要进行相应的改造，详见 [在生产环境中使用 Sentinel 控制台](https://github.com/alibaba/Sentinel/wiki/%E5%9C%A8%E7%94%9F%E4%BA%A7%E7%8E%AF%E5%A2%83%E4%B8%AD%E4%BD%BF%E7%94%A8-Sentinel-%E6%8E%A7%E5%88%B6%E5%8F%B0)。

---

RuleManager will retrieve all rules from the data source (or pushed) and replace all existing rules with new rules, instead of merging into existing rules. If you want to push rules to config center via Sentinel Dashboard, you need to do some refactors.

**Comment by Childe-Chen** [comment]
全量更新不很友好。我最初理解是像dubbo配置一样，参数有覆盖的优先级，而不是都需要配置。如果是全量更新，那么一个需要对MQ多个topic下的tag做资源区分就有些麻烦。
