### ISSUE TITLE
springmvc的adapter（SentinelWebInterceptor）对与@Async这种异步接口 会统计两次吧

### ISSUE THREAD

**Issue by yaoyuandota** [alibaba/Sentinel#1865]
Interceptor 在处理@Async接口的时候，preHandler会执行2次，而afterCompletion只会执行1次，而对sentinel的处理（ SphU.entry）正好放在preHandler里。会不会导致统计了2次？

**Comment by brothelul** [comment]
@yaoyuandota I tried below case, but found the preHandler just excute once. As we know @Async just use AOP to cover the real Spring bean like @Transitional, and the inteceptor is executed before we execute the Spring Bean method. Can you give more detail example for this question? I will try to find the root cause and solve it.

**Comment by sczyh30** [comment]
Hi, any further feedback?

**Comment by yaoyuandota** [comment]
hello,我这边确实发现SentinelWebInterceptor 在异步springmvc时 会走两次，官方默认的adapter无法解决，我们使用了filter。



在 2021-05-06 12:52:03，"Eric Zhao" ***@***.***> 写道：

Hi, any further feedback?

**Comment by renxinlin** [comment]
> 拦截在处理@sync接口的，preHandler会执行一次，而后完成者会执行第1次，而对sentinel的处理（SphU.entry）不会阻塞preHandler会执行2次？

麻烦提供下原异常上下文相关程序,无法复现你描述的场景
