### ISSUE TITLE
DashBoard能够支持按不同应用分权限使用

### ISSUE THREAD

**Issue by wh007** [alibaba/Sentinel#193]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

1.希望支持不同应用分权限控制
2.另外流控目标应用选择增加通过host过滤，现有是多个实例在一起的列表选择，实例多的情况下选项太多实在难以选择
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Hi, for (1) we don't support authorization and authentication for Sentinel Dashboard. We may provide a universal interface for this but you have to implement by yourself. For (2) do you mean group by app-hostname or app name?

**Comment by wh007** [comment]
> Hi, for (1) we don't support authorization and authentication for Sentinel Dashboard. We may provide a universal interface for this but you have to implement by yourself. For (2) do you mean group by app-hostname or app name?

是的，目前所有规则的查询选择列表都是针对于ip+port的，所有app都混在一起，希望能够支持查询列表的级联过滤，比如先选择APP，之后选择APP对应的hostname（ip），进而再选择该host上运行的实例instance.

**Comment by sczyh30** [comment]
Currently the machines are grouped by the application name, so in rule pages, the machines in the list all belongs to the chosen app.

In production the rules are usually stored in remote config centers, so you can set rules for specific app directly (push to all machines) rather than setting one by one by machines. You may have to do some refactors in Sentinel Dashboard to adapt to this (also for app groups or grouped app host).
