### ISSUE TITLE
blog url in awesome-sentinel.md is 404

### ISSUE THREAD

**Issue by xianwdong** [alibaba/Sentinel#2367]
in awesome-sentinel page(https://github.com/alibaba/Sentinel/blob/master/doc/awesome-sentinel.md), the blog url of(Sentinel 为 Dubbo 服务保驾护航 http://dubbo.apache.org/zh-cn/blog/sentinel-introduction-for-dubbo.html) is 404

**Comment by sczyh30** [comment]
It seems that it has been transferred to the new link: https://dubbo.apache.org/zh/blog/2018/07/27/sentinel-为-dubbo-服务保驾护航
Would you like to submit a PR to fix it?

**Comment by xianwdong** [comment]
@sczyh30 I have submitted a PR to fix it.

**Comment by WeisonWei** [comment]
unsubscribe



At 2021-09-12 11:15:54, "xianwdong" ***@***.***> wrote:

@sczyh30 I have submitted a PR to fix it.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
