### ISSUE TITLE
可以添加一个流量控制的注解吗，与SentinelResource 注解搭配使用。

### ISSUE THREAD

**Issue by liyiorg** [alibaba/Sentinel#238]
如题

**Comment by sczyh30** [comment]
Hi, it's not recommended to hard code the rules, because rules are always dynamic in production env. We recommend you to define resources with `@SentinelResource` annotation, then manage rules (e.g. flow rules) in Sentinel Dashboard or via [dynamic rule datasource](https://github.com/alibaba/Sentinel/wiki/Dynamic-Rule-Configuration).

**Comment by liyiorg** [comment]
@sczyh30
