### ISSUE TITLE
Sentinel connect nacos

### ISSUE THREAD

**Issue by gumutianqi** [alibaba/Sentinel#271]
> 目前 Sentinel 对读写数据源的支持不是很优雅，现在有了Alibaba-Nacos;

**希望可以打通：**

1. dashboard 也需要使用 Nacos 服务器发现管理起来；
2. dashboard 编辑后直接保存到 Nacos config；
3. 业务的application 直接从 nacos 读取；
4. 还有 dashboard 监控的数据持久化的 datasource 也是需要考虑的；

目前 nacos-datasource 是有，但是具体怎么和 dashboard 读写以及 sentinel rule json 的 config 结合不是很清晰，也需要自己二次开发 sentinel-dashboard 来将配置推到 nacos，再由 nacos 推给 application；这个流程希望有官方提供更好的连接方式；

**Comment by sczyh30** [comment]
Hi, we'll provide interfaces to integrate config center with Sentinel dashboard as well as the sample and tutorial, but we won't provide a out-of-box solution as the environment may vary in different production env.

**Comment by sczyh30** [comment]
Since 1.4.0 we've provided two interfaces for dynamic rules in dashboard:

`DynamicRuleProvider<T>`: pull rules (or listen to changes) from remote config center
`DynamicRulePublisher<T>`: push rules to remote config center

You can refer to [the document](https://github.com/alibaba/Sentinel/wiki/Sentinel-%E6%8E%A7%E5%88%B6%E5%8F%B0---%E9%9B%86%E7%BE%A4%E9%99%90%E6%B5%81).
