### ISSUE TITLE
The canpass method of DeafultController cannot throw exceptions

### ISSUE THREAD

**Issue by isysc1** [alibaba/Sentinel#3261]
## Issue Description

bug

### Describe what happened (or what feature you want)

If the current priority is true and the flow control mode is fast failure, exceptions should not be thrown, otherwise this priority setting is meaningless.

### Describe what you expected to happen

remove the exception throwing

### How to reproduce it (as minimally and precisely as possible)

1. Make sure your priority is set to true and the flow control mode is fail fast

**Comment by LiYangSir** [comment]
This exception will indeed confuse code readers, but in fact this exception will not be perceived by the user. Sentinel will intercept the exception and perform subsequent processing in {com.alibaba.csp.sentinel.slots.statistic.StatisticSlot#entry}.

I understand that the reason for this is that in order to decouple or return quickly, the outer layer does some priority processing operations, such as event notifications, indicator statistics, etc.

这个异常确实会给代码阅读者带来困惑，但是其实这个异常并不会被用户所感知，Sentinel 会拦截该异常并进行后续处理在{com.alibaba.csp.sentinel.slots.statistic.StatisticSlot#entry} 中。

我理解这么做的原因是为了解耦或者快速返回，有外层去做了一些优先级通过的处理操作，例如事件通知，指标统计等等。
