### ISSUE TITLE
Support export rules to JSON files in Sentinel dashboard

### ISSUE THREAD

**Issue by lipeng1234** [alibaba/Sentinel#443]
后续能否在控制台中加一个一键导出规则配置的功能，把所有流控和降级等规则以json格式文件导出呢？现在的规则配置较多，手动转换为nacos支持的json格式内容比较麻烦，谢谢。

**Comment by sczyh30** [comment]
Hi, Sentinel has provided API command to fetch all rules:

```
http://ip:commandPort/getRules?type=<XXXX>
```

See [the document](https://github.com/alibaba/Sentinel/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8#%E6%9F%A5%E8%AF%A2%E6%9B%B4%E6%94%B9%E8%A7%84%E5%88%99) for more information.

You can also simply refactor the dashboard so that you can directly push rules to Nacos via dashboard. [See here for the tutorial](https://github.com/alibaba/Sentinel/wiki/Sentinel-%E6%8E%A7%E5%88%B6%E5%8F%B0%EF%BC%88%E9%9B%86%E7%BE%A4%E6%B5%81%E6%8E%A7%E7%AE%A1%E7%90%86%EF%BC%89).
