### ISSUE TITLE
Enhancement for circuit breaking

### ISSUE THREAD

**Issue by bingyang001** [alibaba/Sentinel#790]
1，熔断时除了抛出DegradeException异常，**可否给出查询具体是什么业务异常触发了规则，比如：AException,BExcetpion**，导致熔断；单从DegradeException异常看对于业务问题排查帮助不大

2，同一资源熔断规则可否配置多项，并设置优先级，比如：异常数，响应时间，异常比例，多项中谁先达到熔断条件则触发熔断，另外可否只有特定异常才加入到统计中

3，RT_MAX_EXCEED_N = 5 这个可否设置未配置项

4，限流，熔断，系统规则可否加入规则组的概念，这样使用较为方便，只需要把资源加入到规则组即可，减少配置项

5，熔断规则异常比例，count=0.7 (1秒内70%的异常）在一秒内有只有4个异常，也触发了熔断且时间基本是在23:59这是配置有误，还是系统边界值问题，版本1.6release
配置如：
"degradeRules": [
        {
            "count": 0.7,
            "grade": 1,
            "timeWindow": 30
        }
    ]

**Comment by sczyh30** [comment]
Thanks for your suggestion! For 3, the configuration will be supported in 1.7.0. See #789 

For other ideas, maybe we could discuss in #606

**Comment by sczyh30** [comment]
As for 1.7.0, most of these have been improved.

> 1，熔断时除了抛出DegradeException异常，**可否给出查询具体是什么业务异常触发了规则，比如：AException,BExcetpion**，导致熔断；单从DegradeException异常看对于业务问题排查帮助不大

For 1, we're planning to introduce a log for recorded biz exceptions. See #925 for more details.

> 2，同一资源熔断规则可否配置多项，并设置优先级，比如：异常数，响应时间，异常比例，多项中谁先达到熔断条件则触发熔断，另外可否只有特定异常才加入到统计中

Sentinel supports multiple degrade rules for the same resource. Each degrade rule will be checked (priority might not be needed).

Since 1.6.x, you could set the exception type set via the `Tracer. setExceptionsToTrace(xxx)` method.

https://github.com/alibaba/Sentinel/blob/f4d02208cbc1b51c10ab66808744e713b3710677/sentinel-core/src/main/java/com/alibaba/csp/sentinel/Tracer.java#L144-L147

> 3，RT_MAX_EXCEED_N = 5 这个可否设置未配置项

This has been supported since 1.7.0.

> 4，限流，熔断，系统规则可否加入规则组的概念，这样使用较为方便，只需要把资源加入到规则组即可，减少配置项

Good idea. We may open a new issue and do further discussion.

**Comment by sczyh30** [comment]
Circuit breaking has been refactored and enhanced since 1.8.0
