### ISSUE TITLE
Does Sentinel have a plan to support the Service Mesh ecosystem?

### ISSUE THREAD

**Issue by smwyzi** [alibaba/Sentinel#809]
比如有支持Istio/Envoy生态的计划吗？

**Comment by sczyh30** [comment]
Hi, we're planning to support cluster flow control for cloud native and service mesh ecosystem. For Envoy we're planning to provide token server integration with its RLS interface (see #666). And we're working on [Sentinel C++](https://github.com/alibaba/sentinel-cpp) so that we can integrate Sentinel in our customized Envoy filter.

You can also refer to our [roadmap](https://github.com/alibaba/Sentinel/wiki/Roadmap). Discussions and contributions are welcomed.

**Comment by smwyzi** [comment]
Got that，but Envoy has its own RateLimiter and Circuit Breaker etc., what's the difference between Sentinel on Envoy and Envoy's own Flow Control strategy?

**Comment by sczyh30** [comment]
For rate limiting, Envoy only provides a [global rate limiting service](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/global_rate_limiting) interface (based on gRPC) and a sample implementation. Developers need to integrate customized distributed rate limiter (token server in Sentinel) with the Envoy RLS. For circuit breaking, Sentinel provides fundamental circuit breaking strategy for arbitrary customized resources (e.g. error ratio based and response time based), while [Envoy circuit breaking](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/circuit_breaking#arch-overview-circuit-break) is designed for specific transport scenarios (e.g. cluster maximum requests, cluster maximum concurrent connection pools).

**Comment by smwyzi** [comment]
Thanks. 
Happy to see that sentinel can play a larger role in Service Mesh.

**Comment by sczyh30** [comment]
Suggestions and contributions are welcomed :)
