### ISSUE TITLE
ParamFlowRuleEntity json serialization exception

### ISSUE THREAD

**Issue by cookiejoo** [alibaba/Sentinel#876]
我在做配置持久化的时候遇到一个问题.
ParamFlowRuleEntity类中有一个方法在Json反序列化的时候包空指针异常.
如果把这个类的这个方法注释掉就可以了,请看看这是不是一个bug.
因为这个方法是父类方法里面的参数获取,父类已经有了,没必要子类再写一次?.

![image](https://user-images.githubusercontent.com/3397316/60328923-ddc62900-99c1-11e9-9dad-14d6ef2c79c1.png)

![image](https://user-images.githubusercontent.com/3397316/60329091-385f8500-99c2-11e9-8e33-0d99c5197368.png)

**Comment by cdfive** [comment]
This is due to that SpringBoot use `jackson` as its default json framework.

The `@JsonIgnore` in `ParamFlowRuleEntity` class is annotation of `jackson`, not `fastjson`'s.

How about also adding `@JSONField(serialize=false)` of `fastjson` in this entity class? 
@sczyh30 @jasonjoo2010 
But maybe adding two ignore annotation of different json framework seems not simple enough.

@cookiejoo 
Simply, you can use jackson's `ObjectMapper` to do deserializes, like this: 
```java
ObjectMapper objectMapper = new ObjectMapper();
List<ParamFlowRuleEntity> list = objectMapper.readValue(json, objectMapper.getTypeFactory().constructParametricType(List.class, ParamFlowRuleEntity.class));
```

**Comment by cookiejoo** [comment]
> This is due to that SpringBoot use `jackson` as its default json framework.
> 
> The `@JsonIgnore` in `ParamFlowRuleEntity` class is annotation of `jackson`, not `fastjson`'s.
> 
> How about also adding `@JSONField(serialize=false)` of `fastjson` in this entity class?
> @sczyh30 @jasonjoo2010
> But maybe adding two ignore annotation of different json framework seems not simple enough.
> 
> @cookiejoo
> Simply, you can use jackson's `ObjectMapper` to do deserializes, like this:
> 
> ```java
> ObjectMapper objectMapper = new ObjectMapper();
> List<ParamFlowRuleEntity> list = objectMapper.readValue(json, objectMapper.getTypeFactory().constructParametricType(List.class, ParamFlowRuleEntity.class));
> ```

I use this way @JSONField(serialize=false) Solve the problem.
thank you very mush!
